language: php

dist: trusty

sudo: false

php:
  - 7.2
  - 7.3
  - 7.4
  
env:
  global:
    - DEFAULT=1

matrix:
  fast_finish: true

  include:
    - php: 7.2
      env: PHPCS=1 DEFAULT=0
    - php: 7.2
      env: PHPSTAN=1 DEFAULT=0

before_script:
  - if [[ $DEFAULT = 1 ]]; then composer install; fi
  - if [[ $PHPCS = 1 ]]; then composer require cakephp/cakephp-codesniffer; fi
  - if [[ $PHPSTAN = 1 ]]; then composer require phpstan/phpstan:^0.9; fi

script:
  - if [[ $DEFAULT = 1 ]]; then composer test; fi
  - if [[ $PHPCS = 1 ]]; then composer cs-check; fi
  - if [[ $PHPSTAN = 1 ]]; then composer stan-check; fi

notifications:
  email: false

after_success:
    - bash <(curl -s https://codecov.io/bash)
